# 
# Definition of all trackable objects
# Identifier corresponds to Trackable ID set in Tracking Tools
#
rigid_bodies:
    '1':
        pose: youbot/pose
        pose2d: youbot/ground_pose
        child_frame_id: youbot/base_link
        parent_frame_id: world
